### ISSUE TITLE
How to build tcl-duktape with visual studio 2013+ on windows?

### ISSUE THREAD

**Issue by wrenashe** [dbohdan/tcl-duktape#1]
How to build tcl-duktape with visual studio 2013+ on windows?

**Comment by dbohdan** [comment]
Sorry, but I'm afraid you're on your own. I have not built this extension with Visual Studio. Due to its custom `configure` script VS build instructions written for other extensions won't directly apply, either. It should build with [MSYS2](http://msys2.github.io/).

**Comment by wrenashe** [comment]
Got that, thanks. :-)
